### ISSUE TITLE
Semicolon separated commands

### ISSUE THREAD

**Issue by franciszekjuras** [Vrekrer/Vrekrer_scpi_parser#18]
It looks like this library doesn't support semicolon separated commands. I could try extending it to support it, as from my experience many people expect it to work.
Before I get to it, I wanted to ask how difficult it might be considering current architecture? Did you by any chance try to implement this feature before?

**Comment by Vrekrer** [comment]
Thanks for the feedback.

If you wish to help, please see the code in the `SCPI_Parameters::SCPI_Parameters(char* message) ` procedure.
The `not_processed_message` should  return to the buffer and be processed with the `Execute` function

I can see and fix that on the weekend.
