### ISSUE TITLE
Issues with 0.4.2 and 0.5.0-pre release on 2 character commands

### ISSUE THREAD

**Issue by nmaas87** [Vrekrer/Vrekrer_scpi_parser#28]
Hello Vrekrer,
I have found an issue in using very short commands.

E.g. if I registered the commands
:XOCX, :XOCX?, :XOD, :XOD?, :XO and :XO?
the first 4 commands will run without issue, both setter and getters.
However, commands ":XO" and ":XO?" will be hashed with the value 255 on 0.4.2.
The "setter" command :XO will still work, but :XO? will not.

On 0.5.0, both commands will not work, which is probably better, as it seems to be a hash collision.

I set the values to very high in hopes to get the issue resolved, e.g. in the parser header file:

````
/// Max branch size of the command tree and max number of parameters.
#ifndef SCPI_ARRAY_SYZE
  #define SCPI_ARRAY_SYZE 72
#endif

/// Max number of valid tokens.
#ifndef SCPI_MAX_TOKENS
  #define SCPI_MAX_TOKENS 90
#endif

/// Max number of registered commands.
#ifndef SCPI_MAX_COMMANDS
  #define SCPI_MAX_COMMANDS 120
#endif

/// Max number of registered special commands.
#ifndef SCPI_MAX_SPECIAL_COMMANDS
  #define SCPI_MAX_SPECIAL_COMMANDS 0
#endif

/// Length of the message buffer.
#ifndef SCPI_BUFFER_LENGTH
  #define SCPI_BUFFER_LENGTH 128
#endif

/// Integer size used for hashes.
#ifndef SCPI_HASH_TYPE
  #define SCPI_HASH_TYPE uint16_t
#endif

[...]
  ///Magic number used for hashing the commands
  scpi_hash_t hash_magic_number = 16001;
  ///Magic offset used for hashing the commands
  scpi_hash_t hash_magic_offset = 37;
````

any ideas on how to resolve this issue? And thanks a lot! :)

**Comment by Vrekrer** [comment]
Thank you for the bug report.
