### ISSUE TITLE
Vrekrer SCPI Parse using ethernet

### ISSUE THREAD

**Issue by bsteeldkdp** [Vrekrer/Vrekrer_scpi_parser#36]
Hi.
I'm trying to use the SCPI parser on e ethernet connection instead of the serial interface, but I'm having some issues getting this to work.
is there a simple way for this to work and change from serial to ethernet ??

Current code looks like this:
/*
  Web Server

 A simple web server that shows the value of the analog input pins.
 using an Arduino Wiznet Ethernet shield.

 Circuit:
 * Ethernet shield attached to pins 10, 11, 12, 13
 * Analog inputs attached to pins A0 through A5 (optional)

 created 18 Dec 2009
 by David A. Mellis
 modified 9 Apr 2012
 by Tom Igoe
 modified 02 Sept 2015
 by Arturo Guadalupi
 
 */

#include <SPI.h>
#include <Ethernet.h>
#include <Vrekrer_scpi_parser.h>
SCPI_Parser my_instrument;

// Enter a MAC address and IP address for your controller below.
// The IP address will be dependent on your local network:
byte mac[] = {
  0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED
};
IPAddress ip(192, 168, 100, 111);

// Initialize the Ethernet server library
// with the IP address and port you want to use
// (port 80 is default for HTTP):
EthernetServer server(80);

String sampledata;

void setup() {

  my_instrument.RegisterCommand(F("*IDN?"), &Identify);
  //my_instrument.SetCommandTreeBase(F("SYSTem:LED"));
    //my_instrument.RegisterCommand(F(":BRIGhtness"), &SetBrightness);
    //my_instrument.RegisterCommand(F(":BRIGhtness?"), &GetBrightness);
    //my_instrument.RegisterCommand(F(":BRIGhtness:INCrease"), &IncDecBrightness);
    //my_instrument.RegisterCommand(F(":BRIGhtness:DECrease"), &IncDecBrightness);

  // You can use Ethernet.init(pin) to configure the CS pin
  //Ethernet.init(10);  // Most Arduino shields
  //Ethernet.init(5);   // MKR ETH shield
  //Ethernet.init(0);   // Teensy 2.0
  //Ethernet.init(20);  // Teensy++ 2.0
  //Ethernet.init(15);  // ESP8266 with Adafruit Featherwing Ethernet
  //Ethernet.init(33);  // ESP32 with Adafruit Featherwing Ethernet

  // Open serial communications and wait for port to open:
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }
  Serial.println("Ethernet WebServer Example");

  // start the Ethernet connection and the server:
  Ethernet.begin(mac, ip);

  // Check for Ethernet hardware present
  if (Ethernet.hardwareStatus() == EthernetNoHardware) {
    Serial.println("Ethernet shield was not found.  Sorry, can't run without hardware. :(");
    while (true) {
      delay(1); // do nothing, no point running without Ethernet hardware
    }
  }
  if (Ethernet.linkStatus() == LinkOFF) {
    Serial.println("Ethernet cable is not connected.");
  }

  // start the server
  server.begin();
  Serial.print("server is at ");
  Serial.println(Ethernet.localIP());
}

void loop() {
//    my_instrument.ProcessInput(Serial, "\n");
  // listen for incoming clients
  EthernetClient client = server.available();
  if (client) 
  {
    Serial.println("new client");
    // an http request ends with a blank line
    boolean currentLineIsBlank = true;
    while (client.connected()) 
    {
      if (client.available()) 
      {
        char c = client.read();
        Serial.print(c);
        client.println("Vrekrer,SCPI Dimmer,#00," VREKRER_SCPI_VERSION);
        Serial.println("Vrekrer,SCPI Dimmer,#00," VREKRER_SCPI_VERSION);
        sampledata.concat(c);
        // if you've gotten to the end of the line (received a newline
        // character) and the line is blank, the http request has ended,
        // so you can send a reply
        if (c == '\n') 
        {
          // you're starting a new line
          currentLineIsBlank = true;
          Serial.println("Blank");
          my_instrument.ProcessInput(Serial, "\n");
        } 
        else if (c != '\r') 
        {
          // you've gotten a character on the current line
          currentLineIsBlank = false;
          Serial.println("Not Blank");
        }
      }
    }
    // give the web browser time to receive the data
    delay(1);
    // close the connection:
    client.stop();
    Serial.println("client disconnected");
  }
}

void Identify(SCPI_C commands, SCPI_P parameters, Stream& interface) {
  interface.println(F("Vrekrer,SCPI Dimmer,#00," VREKRER_SCPI_VERSION));
  //*IDN? Suggested return string should be in the following format:
  // "<vendor>,<model>,<serial number>,<firmware>"
}

**Comment by Vrekrer** [comment]
Hello

Take a look at these examples

[Arduino Ethernet Shield Voltmeter](https://gist.github.com/Vrekrer/0f0bbc0cb9696ec8748b4ddfef425f06)

[ENC28J60 Ethernet Shield Voltmeter](https://github.com/Vrekrer/Vrekrer_Voltmeter)

[Wi-Fi ESP32 Dimmer](https://gist.github.com/Vrekrer/4dbbf4368071becb5fc32b97f321f446)

[Wi-Fi ESP32 Data Logger](https://github.com/Vrekrer/DataLogger/blob/main/Instrument/Instrument.ino)

If you need more help, feel free to ask!
